defmodule Ankra.Repo.Migrations.UpdateCustomers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:customers, [:email], name: "customers_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:customers, [:email], name: "customers_unique_email_index")
  end
end
